// Game content: buildings, upgrades, kiln (prestige) upgrades, relics,
// doctrines, trials, achievements, journal entries and the Great Hourglass.
import { CRYSTAL, STONE, PRISM } from './sim.js';

export const ROUNDS_PER_SEC = 30;
export const START_SIZE = 5;

export const BUILDINGS = {
  hourglass: {
    kind: -1, name: 'Hourglass', icon: '⧗', base: 10, growth: 1.15,
    desc: 'Pours a steady trickle of sand. New hourglasses join your stack; drag the stack to choose where the sand falls.',
  },
  crystal: {
    kind: CRYSTAL, name: 'Crystal', icon: '◆', base: 1500, growth: 1.9, unlock: 'crystal',
    desc: 'Grows only on geodes. Topples on its cell are worth far more dust, and richer geodes grow better crystals.',
  },
  stone: {
    kind: STONE, name: 'Stone', icon: '●', base: 300, growth: 1.8, unlock: 'stone',
    desc: 'Sand bounces off stones. Wall in your pour, leave a gap, and sand lingers, toppling again and again.',
  },
  prism: {
    kind: PRISM, name: 'Prism', icon: '▲', base: 3e8, growth: 3, unlock: 'prism',
    desc: 'Every crystal it touches (not diagonally) has its multiplier doubled.',
  },
};
export const KIND_TO_BUILDING = { [CRYSTAL]: 'crystal', [STONE]: 'stone', [PRISM]: 'prism' };

// Owning this many hourglasses doubles their flow (each milestone).
export const HG_MILESTONES = Array.from({ length: 80 }, (_, i) => 25 * (i + 1));

// ---------------------------------------------------------------- dust upgrades
// Reset on every sweep. `req`: other upgrades; `kreq`: a kiln upgrade; `need`: an unlocked flag.
// fx keys: rate, hand, dust, crystalMul, glass, quake, quakeCd, gleamFreq, gleamPow, dig, geode, spring
// (multipliers); crystal, prism, stones (additive); size; unlock.
export const UPGRADES = [
  { id: 'u_hands', name: 'Cupped Hands', cost: 30, fx: { hand: 3 },
    desc: 'Each click drops 3 grains instead of 1.' },
  { id: 'u_fine', name: 'Fine Sand', cost: 200, fx: { rate: 2 },
    desc: 'Hourglasses pour twice as fast.' },
  { id: 'u_t7', name: 'Wider Table', cost: 1200, fx: { size: 7 },
    desc: 'Uncover the table to 7×7. Sand travels further, and who knows what is out there.' },
  { id: 'u_sift', name: 'Sifting', cost: 5000, fx: { dust: 2 }, req: ['u_t7'],
    desc: 'Every topple gives twice the dust.' },
  { id: 'u_crystal', name: 'Crystals', cost: 15000, fx: { unlock: 'crystal' }, req: ['u_t7'],
    desc: 'Grow crystals on geodes. Topples on a crystal are worth ×3, more on richer geodes.' },
  { id: 'u_spade', name: 'Spade', cost: 30000, fx: { dig: 2 }, req: ['u_t7'],
    desc: 'Dig sites yield twice as fast.' },
  { id: 'u_finer', name: 'Finer Sand', cost: 50000, fx: { rate: 2 }, req: ['u_fine'],
    desc: 'Hourglasses pour twice as fast.' },
  { id: 'u_t9', name: 'Wider Table II', cost: 150000, fx: { size: 9 }, req: ['u_t7'],
    desc: 'Uncover the table to 9×9.' },
  { id: 'u_quake', name: 'Quake', cost: 250000, fx: { unlock: 'quake' }, req: ['u_t9'],
    desc: 'Unlock the Quake: shake the table, scattering half a minute of sand across every cell.' },
  { id: 'u_facet', name: 'Cut Facets', cost: 800000, fx: { crystal: 3 }, req: ['u_crystal'],
    desc: 'Crystals give +3 to their multiplier.' },
  { id: 'u_mortar', name: 'Mortar', cost: 1.5e6, fx: { stones: 3 }, need: 'stone',
    desc: '+3 stones.' },
  { id: 'u_glimmer', name: 'Glimmer', cost: 2e6, fx: { unlock: 'gleam' }, req: ['u_t9'],
    desc: 'Sometimes a grain catches the light. Click gleaming grains for a reward.' },
  { id: 'u_t11', name: 'Wider Table III', cost: 4e6, fx: { size: 11 }, req: ['u_t9'],
    desc: 'Uncover the table to 11×11.' },
  { id: 'u_winnow', name: 'Winnowing', cost: 6e6, fx: { dust: 2 }, req: ['u_sift'],
    desc: 'Every topple gives twice the dust.' },
  { id: 'u_finest', name: 'Finest Sand', cost: 1.2e7, fx: { rate: 2 }, req: ['u_finer'],
    desc: 'Hourglasses pour twice as fast.' },
  { id: 'u_geology', name: 'Geology', cost: 2e7, fx: { geode: 1.5 }, req: ['u_crystal', 'u_t9'],
    desc: 'Geodes are 50% richer.' },
  { id: 'u_t13', name: 'Wider Table IV', cost: 4e7, fx: { size: 13 }, req: ['u_t11'],
    desc: 'Uncover the table to 13×13.' },
  { id: 'u_brill', name: 'Brilliant Cut', cost: 1.2e8, fx: { crystal: 6 }, req: ['u_facet'],
    desc: 'Crystals give +6 to their multiplier.' },
  { id: 'u_sieve', name: 'Sieve', cost: 5e8, fx: { dust: 2 }, req: ['u_winnow'],
    desc: 'Every topple gives twice the dust.' },
  { id: 'u_lodestone', name: 'Lodestone', cost: 1.2e9, fx: { stoneGlow: 1.25 }, need: 'stone',
    desc: 'Topples beside a stone are worth ×1.25 (and again for each more stone beside them).' },
  { id: 'u_rumble', name: 'Rumble', cost: 2.5e9, fx: { quake: 2 }, req: ['u_quake'],
    desc: 'Quakes are twice as strong.' },
  // ---- revealed by kiln upgrades and relics
  { id: 'u_aftershock', name: 'Aftershock', cost: 6e10, fx: { unlock: 'aftershock' }, req: ['u_quake'], kreq: 'k_seismic',
    desc: 'For 10 seconds after a quake, every topple gives triple dust.' },
  { id: 'u_t15', name: 'Long Table', cost: 5e11, fx: { size: 15 }, req: ['u_t13'], kreq: 'k_long',
    desc: 'Uncover the table to 15×15.' },
  { id: 'u_temper', name: 'Tempering', cost: 2e13, fx: { dust: 3 }, req: ['u_winnow'], kreq: 'k_long',
    desc: 'Every topple gives triple dust.' },
  { id: 'u_bore', name: 'Bore Holes', cost: 2e12, fx: { spring: 2 }, need: 'seen_spring',
    desc: 'Springs pour twice as much.' },
  { id: 'u_lustre', name: 'Lustre', cost: 2.5e13, fx: { gleamPow: 2 }, req: ['u_glimmer'], kreq: 'k_seismic',
    desc: 'Gleam rewards are twice as strong.' },
  { id: 'u_t17', name: 'Longer Table', cost: 1.5e15, fx: { size: 17 }, req: ['u_t15'], kreq: 'k_long',
    desc: 'Uncover the table to 17×17.' },
  { id: 'u_silt', name: 'Silt', cost: 1.2e16, fx: { rate: 2 }, req: ['u_finest'], kreq: 'k_long',
    desc: 'Hourglasses pour twice as fast.' },
  { id: 'u_shovel', name: 'Shovel', cost: 2e16, fx: { dig: 2 }, req: ['u_spade'], kreq: 'k_long',
    desc: 'Dig sites yield twice as fast.' },
  { id: 'u_marquise', name: 'Marquise Cut', cost: 2e12, fx: { crystal: 15 }, req: ['u_brill'], need: 'prism',
    desc: 'Crystals give +15 to their multiplier.' },
  { id: 'u_refract', name: 'Refraction', cost: 7e16, fx: { prism: 1 }, req: ['u_marquise'], need: 'prism',
    desc: 'Prisms triple the crystals they touch, instead of doubling them.' },
  { id: 'u_t19', name: 'Great Table', cost: 4e15, fx: { size: 19 }, req: ['u_t17'], kreq: 'k_vast',
    desc: 'Uncover the table to 19×19.' },
  { id: 'u_loess', name: 'Loess', cost: 3e17, fx: { dust: 5 }, req: ['u_temper'], kreq: 'k_vast',
    desc: 'Every topple gives five times the dust.' },
  { id: 'u_t21', name: 'Grand Table', cost: 3e18, fx: { size: 21 }, req: ['u_t19'], kreq: 'k_vast',
    desc: 'Uncover the table to 21×21.' },
  { id: 'u_powder', name: 'Powder', cost: 6e21, fx: { rate: 3 }, req: ['u_silt'], kreq: 'k_vast',
    desc: 'Hourglasses pour three times as fast.' },
  { id: 'u_t23', name: 'Endless Table', cost: 1e16, fx: { size: 23 }, req: ['u_t21'], kreq: 'k_horizon',
    desc: 'Uncover the table to 23×23.' },
  { id: 'u_rose', name: 'Rose Cut', cost: 4e23, fx: { crystal: 60 }, req: ['u_marquise'], kreq: 'k_horizon',
    desc: 'Crystals give +60 to their multiplier.' },
  { id: 'u_t25', name: 'Horizon Table', cost: 1.2e28, fx: { size: 25 }, req: ['u_t23'], kreq: 'k_horizon',
    desc: 'Uncover the whole table: 25×25.' },
  { id: 'u_starlight', name: 'Starlight', cost: 5e29, fx: { dust: 10 }, req: ['u_loess'], kreq: 'k_horizon',
    desc: 'Every topple gives ten times the dust.' },
];
export const UPGRADE_MAP = Object.fromEntries(UPGRADES.map(u => [u.id, u]));

// ---------------------------------------------------------------- kiln
// Glass upgrades. Permanent (survive sweeps).
export const KILN = [
  // tier I
  { id: 'k_warm', name: 'Warm Glass', cost: 6, fx: { dust: 3 }, row: 0,
    desc: 'Every topple gives triple dust. Forever.' },
  { id: 'k_glasshg', name: 'Glass Hourglasses', cost: 6, fx: { rate: 2 }, row: 0,
    desc: 'Hourglasses pour twice as fast.' },
  { id: 'k_memory', name: 'Memory of Sand', cost: 25, fx: { memory: 1 }, row: 0,
    desc: 'Start each run with Cupped Hands, Fine Sand and a 7×7 table.' },
  // tier II
  { id: 'k_anneal', name: 'Annealing', cost: 60, fx: { crystalMul: 2 }, row: 1, req: ['k_warm'],
    desc: 'Crystal multipliers are doubled.' },
  { id: 'k_survey', name: 'Surveyor\'s Rod', cost: 80, fx: { dig: 2 }, row: 1, req: ['k_warm'],
    desc: 'Dig sites yield twice as fast.' },
  { id: 'k_apprentice', name: 'Apprentice', cost: 100, fx: { auto: 'hourglass' }, row: 1, req: ['k_glasshg'],
    desc: 'Automatically buys hourglasses when you can afford them.' },
  { id: 'k_seismic', name: 'Seismology', cost: 100, fx: { quake: 2, quakeCd: 0.75 }, row: 1, req: ['k_memory'],
    desc: 'Quakes are twice as strong and recharge 25% faster. Reveals new dust upgrades.' },
  { id: 'k_long', name: 'The Long Table', cost: 120, fx: { reveal: 1 }, row: 1, req: ['k_memory'],
    desc: 'Reveals new dust upgrades, including 15×15 and 17×17 tables.' },
  // tier III
  { id: 'k_blow', name: 'Glassblowing', cost: 400, fx: { glass: 2 }, row: 2, req: ['k_apprentice'],
    desc: 'Sweeps yield twice as much glass.' },
  { id: 'k_cairn', name: 'Cairn', cost: 1200, fx: { stones: 6 }, row: 2, req: ['k_long'],
    desc: '+6 stones.' },
  { id: 'k_journeyman', name: 'Journeyman', cost: 3000, fx: { auto: 'upgrades' }, row: 2, req: ['k_blow'],
    desc: 'Automatically buys dust upgrades when you can afford them.' },
  { id: 'k_lapidary', name: 'Lapidary', cost: 4000, fx: { geode: 1.5 }, row: 2, req: ['k_anneal'],
    desc: 'Geodes are 50% richer.' },
  { id: 'k_deep', name: 'Deep Memory', cost: 6000, fx: { memory: 2 }, row: 2, req: ['k_memory', 'k_journeyman'],
    desc: 'Start each run with every early dust upgrade, up to an 11×11 table.' },
  // tier IV
  { id: 'k_artisan', name: 'Artisan', cost: 5000, fx: { auto: 'crystal' }, row: 3, req: ['k_journeyman'],
    desc: 'Automatically buys crystals and prisms when you can afford them.' },
  { id: 'k_seismograph', name: 'Seismograph', cost: 6000, fx: { auto: 'quake' }, row: 3, req: ['k_seismic'],
    desc: 'Automatically triggers quakes when they are ready.' },
  { id: 'k_wells', name: 'Wellwork', cost: 6000, fx: { spring: 2 }, row: 3, req: ['k_survey'],
    desc: 'Springs pour twice as much.' },
  { id: 'k_vast', name: 'Vast Tables', cost: 30000, fx: { reveal: 2 }, row: 3, req: ['k_long'],
    desc: 'Reveals new dust upgrades, including 19×19 and 21×21 tables.' },
  { id: 'k_tremor', name: 'Tremor Doctrine', cost: 30000, fx: { unlock: 'tremor' }, row: 3, req: ['k_seismic'],
    desc: 'A fourth doctrine, for those who like to shake things. (Needs doctrines.)' },
  { id: 'k_kiln2', name: 'Bellows', cost: 4e5, fx: { glass: 2 }, row: 3, req: ['k_blow'],
    desc: 'Sweeps yield twice as much glass.' },
  { id: 'k_quarry', name: 'Quarry', cost: 8e5, fx: { stones: 10 }, row: 3, req: ['k_cairn'],
    desc: '+10 stones.' },
  // tier V
  { id: 'k_cascade', name: 'Cascade', cost: 5e6, fx: { tables: 1 }, row: 4, req: ['k_vast'],
    desc: 'A second table beneath the first. Sand that falls from the first pours onto the second.' },
  { id: 'k_horizon', name: 'Horizon', cost: 5e8, fx: { reveal: 3 }, row: 4, req: ['k_vast'],
    desc: 'Reveals the last dust upgrades, including 23×23 and 25×25 tables.' },
  { id: 'k_cascade2', name: 'Third Table', cost: 3e10, fx: { tables: 1 }, row: 4, req: ['k_cascade'],
    desc: 'A third table, beneath the second.' },
  { id: 'k_furnace', name: 'Furnace', cost: 4e10, fx: { glass: 3 }, row: 4, req: ['k_kiln2'],
    desc: 'Sweeps yield three times as much glass.' },
  { id: 'k_great', name: 'The Plans', cost: 6e11, fx: { unlock: 'great' }, row: 4, req: ['k_cascade2'],
    desc: 'Plans for an hourglass larger than the house. Larger than the sky.' },
];
export const KILN_MAP = Object.fromEntries(KILN.map(k => [k.id, k]));

// Repeatable glass sink.
export const POLISH = { id: 'k_polish', name: 'Polish', base: 5, growth: 4, mult: 2,
  desc: 'Every topple gives twice the dust. Can be bought again and again.' };

// ---------------------------------------------------------------- relics
// Found by digging, in the order below. `ring` is how far from the centre a dig
// site must be to hold the relic: the later relics lie deeper, under the
// outer rings that only the largest tables uncover. Sites with nothing left
// for them hold caches of dust instead.
export const RELICS = [
  { id: 'chisel', ring: 0, name: 'Mason\'s Chisel', icon: '⚒', fx: { unlock: 'stone', stones: 6 },
    desc: 'You can set stones: 6 of them. Sand bounces off stones; wall in your pour, but leave a gap.',
    lore: 'Worn smooth at the handle. Someone shaped a great deal of stone with it.' },
  { id: 'lens', ring: 0, name: 'Cracked Lens', icon: '◎', fx: { crystalMul: 2 },
    desc: 'Crystal multipliers ×2.',
    lore: 'Through it, every grain looks like a boulder.' },
  { id: 'ledger', ring: 2, name: 'The Keeper\'s Ledger', icon: '▤', fx: { unlock: 'doctrine' },
    desc: 'Choose a doctrine each time you sweep.',
    lore: 'Columns of figures, then one line, underlined twice: "There is more than one way to keep a table."' },
  { id: 'shard', ring: 2, name: 'Prism Shard', icon: '▲', fx: { unlock: 'prism' },
    desc: 'Unlocks prisms. A prism doubles every crystal it touches.',
    lore: 'It splits the lamplight into colours you do not have names for.' },
  { id: 'trowel', ring: 3, name: 'Brass Trowel', icon: '⌂', fx: { dig: 2 },
    desc: 'Dig twice as fast.',
    lore: 'Green with age, sharp as the day it was made.' },
  { id: 'map', ring: 3, name: 'Folded Map', icon: '⌗', fx: { choices: 3 },
    desc: 'Choose between three tables when you sweep, instead of two.',
    lore: 'A map of tables. More tables than you thought there could be.' },
  { id: 'bone', ring: 4, name: 'Bone Hourglass', icon: '⧗', fx: { startHg: 10 },
    desc: 'Start every run with 10 hourglasses.',
    lore: 'The sand inside never seems to run out.' },
  { id: 'pick', ring: 4, name: 'Pickaxe', icon: '⛏', fx: { pick: 3, unlock: 'shape' },
    desc: 'Break bedrock with the Shape tool: up to 3 cells on each table.',
    lore: 'Heavier than it looks. Everything here is.' },
  { id: 'nail', ring: 5, name: 'Bent Nail', icon: '⌒', fx: { unlock: 'fold' },
    desc: 'Fold the table so its east and west edges meet. Sand only falls off the north and south.',
    lore: 'Bent double, as if something folded around it.' },
  { id: 'clock', ring: 5, name: 'Water Clock', icon: '◷', fx: { spring: 2 },
    desc: 'Springs pour twice as much.',
    lore: 'It measures time in drips, which is to say, slowly.' },
  { id: 'vane', ring: 6, name: 'Weathervane', icon: '➶', fx: { vane: 1, unlock: 'shape' },
    desc: 'Turn slopes with the Shape tool.',
    lore: 'It points wherever you tell it to. Sand is less obliging.' },
  { id: 'plumb', ring: 6, name: 'Plumb Line', icon: '⊥', fx: { stones: 6 },
    desc: '+6 stones.',
    lore: 'True and straight, in a world of sand that is neither.' },
  { id: 'drum', ring: 6, name: 'Hide Drum', icon: '◍', fx: { quake: 2 },
    desc: 'Quakes are twice as strong.',
    lore: 'You tap it once and the whole table shivers.' },
  { id: 'tablet', ring: 7, name: 'Clay Tablet', icon: '▦', fx: { unlock: 'trials' },
    desc: 'Unlocks Trials: runs with strange rules and permanent rewards.',
    lore: 'Six rules pressed into clay, and a seventh scratched out.' },
  { id: 'spoon', ring: 7, name: 'Silver Spoon', icon: '♁', fx: { gleamFreq: 2 },
    desc: 'Gleams appear twice as often.',
    lore: 'Polished by a lifetime of being looked at.' },
  { id: 'seed', ring: 7, name: 'Seed Crystal', icon: '◆', fx: { geode: 1.5 },
    desc: 'Geodes are 50% richer.',
    lore: 'Plant it and it grows. Slowly. Over a thousand years.' },
  { id: 'ember', ring: 7, name: 'Ember in a Jar', icon: '✺', fx: { glass: 2 },
    desc: 'Sweeps yield twice as much glass.',
    lore: 'Still warm. The kiln has been lit before, many times.' },
  { id: 'compass', ring: 8, name: 'Compass', icon: '✣', fx: { compass: 1, dig: 1.5 },
    desc: 'See every table in full before you choose it, and dig 50% faster.',
    lore: 'It does not point north. It points down.' },
  { id: 'spectacles', ring: 8, name: 'Keeper\'s Spectacles', icon: '∞', fx: { perRelic: 1.1 },
    desc: 'Dust ×1.1 for every relic you have found.',
    lore: 'Your prescription, exactly.' },
  { id: 'coin', ring: 8, name: 'Old Coin', icon: '●', fx: { dust: 3 },
    desc: 'Dust ×3.',
    lore: 'Worn blank on both sides. Heads, or tails, or neither.' },
  { id: 'shell', ring: 9, name: 'Spiral Shell', icon: '@', fx: { rate: 2 },
    desc: 'Hourglasses pour twice as fast.',
    lore: 'Hold it to your ear: not the sea, but sand, falling.' },
  { id: 'fork', ring: 9, name: 'Tuning Fork', icon: 'Ψ', fx: { prism: 0.5 },
    desc: 'Prisms are 50% stronger.',
    lore: 'Strike it on the table and every crystal answers.' },
  { id: 'dollar', ring: 9, name: 'Sand Dollar', icon: '✿', fx: { dust: 5 },
    desc: 'Dust ×5.',
    lore: 'Currency, of a kind. The sand accepts it.' },
  { id: 'letter', ring: 10, name: 'The Keeper\'s Letter', icon: '✉', fx: { dust: 10 },
    desc: 'Dust ×10. And a letter.',
    lore: '"If you are reading this, you found the last of my things. I hid them for you, though I did not know your name. Build it. Turn it. Then start again, gently."' },
];
export const RELIC_MAP = Object.fromEntries(RELICS.map(r => [r.id, r]));

// Topples needed to dig a site: grows with distance from the centre, and with
// every relic already found (digging gets faster as you go, so this keeps each
// dig a few minutes' work all game long).
export function digNeed(ring, relicsFound) {
  return Math.round(1000 * (1 + 0.5 * ring) * Math.pow(1.15, relicsFound));
}

// ---------------------------------------------------------------- doctrines
export const DOCTRINES = {
  flow: { name: 'Flow', icon: '⧗', desc: 'Hourglasses pour three times as fast.' },
  facet: { name: 'Facet', icon: '◆', desc: 'Crystal multipliers are tripled.' },
  patience: { name: 'Patience', icon: '◌', desc: 'Dust multiplier grows the longer this run lasts: ×1 rising to ×8 over 40 minutes.' },
  delve: { name: 'Delve', icon: '⛏', desc: 'Dig three times as fast; every relic found this run also gives a burst of glass.' },
  tremor: { name: 'Tremor', icon: '≋', req: 'tremor', desc: 'Quakes are twice as strong and recharge twice as fast. Gleams appear twice as often.' },
};

// ---------------------------------------------------------------- trials
// goal: dust earned this run
export const TRIALS = [
  { id: 't_narrow', name: 'The Narrow Table', goal: 4e14,
    rule: 'The table can never grow beyond 9×9.',
    reward: 'Crystal multipliers ×2.', fx: { crystalMul: 2 } },
  { id: 't_still', name: 'Still Hands', goal: 1.5e16,
    rule: 'No clicking, no quakes, no gleams. Only hourglasses (and springs).',
    reward: 'Hourglasses pour twice as fast.', fx: { rate: 2 } },
  { id: 't_wind', name: 'The East Wind', goal: 2.5e19,
    rule: 'Every topple sends two grains east, one north, one south and none west. Slopes still lean their own way.',
    reward: 'Folded tables give ×3 dust.', fx: { foldBonus: 3 } },
  { id: 't_crumble', name: 'Crumbling Sand', goal: 2.5e21,
    rule: 'Every topple loses one of its four grains to the wind.',
    reward: '+8 stones, and stones make neighbouring topples worth ×1.5.', fx: { stones: 8, stoneGlow: 1.5 } },
  { id: 't_scatter', name: 'Scattered Glass', goal: 1.2e27,
    rule: 'Hourglasses drop their sand on random cells.',
    reward: 'Gleams appear twice as often and last longer.', fx: { gleamFreq: 2 } },
  { id: 't_glassless', name: 'Glassless', goal: 2.5e18,
    rule: 'Kiln upgrades have no effect (automation and memory still work). Relics still do.',
    reward: 'Sweeps yield ×3 glass.', fx: { glass: 3 } },
];
export const TRIAL_MAP = Object.fromEntries(TRIALS.map(t => [t.id, t]));

// ---------------------------------------------------------------- the Great Hourglass
export const GREAT = [
  { id: 'g_frame', name: 'The Frame', glass: 1.5e12, sand: 0,
    desc: 'Four pillars of black wood.', reward: 'Dust ×10.', fx: { dust: 10 } },
  { id: 'g_lower', name: 'The Lower Bulb', glass: 3e12, sand: 0,
    desc: 'A bulb to catch everything that falls.', reward: 'Glass ×2. Sand falling from your last table is now collected.', fx: { glass: 2, collectSand: 1 } },
  { id: 'g_neck', name: 'The Neck', glass: 0, sand: 4e9, trials: true,
    desc: 'Narrow enough for one grain at a time. Requires every trial completed.', reward: 'Hourglasses pour ×5 faster.', fx: { rate: 5 } },
  { id: 'g_upper', name: 'The Upper Bulb', glass: 2e12, sand: 0,
    desc: 'A bulb to hold everything that will fall.', reward: 'Dust ×100.', fx: { dust: 100 } },
  { id: 'g_fill', name: 'The Filling', glass: 0, sand: 1.2e18,
    desc: 'Pour in the sand of every table you have kept.', reward: 'The Great Hourglass is complete.', fx: {} },
];

// ---------------------------------------------------------------- achievements
// Each achievement: +3% dust (additive).
export const ACH_BONUS = 0.03;
const relicCount = g => Object.keys(g.s.relics).length;
export const ACHIEVEMENTS = [
  { id: 'a_first', name: 'First Fall', desc: 'Topple a cell.', check: g => g.s.stats.topples >= 1 },
  { id: 'a_t1k', name: 'Restless', desc: 'Topple 1,000 times in total.', check: g => g.s.stats.topples >= 1e3 },
  { id: 'a_t1m', name: 'Landslide', desc: 'Topple a million times in total.', check: g => g.s.stats.topples >= 1e6 },
  { id: 'a_t1b', name: 'Erosion', desc: 'Topple a billion times in total.', check: g => g.s.stats.topples >= 1e9 },
  { id: 'a_t1t', name: 'Geology', desc: 'Topple a trillion times in total.', check: g => g.s.stats.topples >= 1e12 },
  { id: 'a_hg1', name: 'Timekeeper', desc: 'Own an hourglass.', check: g => g.s.owned.hourglass >= 1 },
  { id: 'a_hg10', name: 'Clockmaker', desc: 'Own 10 hourglasses.', check: g => g.s.owned.hourglass >= 10 },
  { id: 'a_hg25', name: 'Horologist', desc: 'Own 25 hourglasses.', check: g => g.s.owned.hourglass >= 25 },
  { id: 'a_hg100', name: 'Time Enough', desc: 'Own 100 hourglasses.', check: g => g.s.owned.hourglass >= 100 },
  { id: 'a_hg300', name: 'All the Time in the World', desc: 'Own 300 hourglasses.', check: g => g.s.owned.hourglass >= 300 },
  { id: 'a_cr1', name: 'Facet', desc: 'Grow a crystal.', check: g => g.s.owned.crystal >= 1 },
  { id: 'a_cr8', name: 'Geode', desc: 'Grow 8 crystals in one run.', check: g => g.s.owned.crystal >= 8 },
  { id: 'a_cr16', name: 'Cave of Wonders', desc: 'Grow 16 crystals in one run.', check: g => g.s.owned.crystal >= 16 },
  { id: 'a_rich', name: 'Mother Lode', desc: 'Grow a crystal on a geode of richness ×3 or more.', check: g => g.s.flags.richCrystal },
  { id: 'a_wave25', name: 'Ripple', desc: '25 cells topple in a single moment.', check: g => g.s.stats.maxWave >= 25 },
  { id: 'a_wave80', name: 'Swell', desc: '80 cells topple in a single moment.', check: g => g.s.stats.maxWave >= 80 },
  { id: 'a_wave200', name: 'Tsunami', desc: '200 cells topple in a single moment.', check: g => g.s.stats.maxWave >= 200 },
  { id: 'a_hand', name: 'Sandbox', desc: 'Drop 500 grains by hand.', check: g => g.s.stats.handGrains >= 500 },
  { id: 'a_t13', name: 'Room to Breathe', desc: 'Uncover a 13×13 table.', check: g => g.maxSize() >= 13 },
  { id: 'a_t21', name: 'Expanse', desc: 'Uncover a 21×21 table.', check: g => g.maxSize() >= 21 },
  { id: 'a_t25', name: 'Horizon', desc: 'Uncover a whole table.', check: g => g.maxSize() >= 25 },
  { id: 'a_quake1', name: 'Tremor', desc: 'Trigger a quake.', check: g => g.s.stats.quakes >= 1 },
  { id: 'a_quake50', name: 'Fault Line', desc: 'Trigger 50 quakes.', check: g => g.s.stats.quakes >= 50 },
  { id: 'a_gleam1', name: 'Glint', desc: 'Catch a gleaming grain.', check: g => g.s.stats.gleams >= 1 },
  { id: 'a_gleam25', name: 'Magpie', desc: 'Catch 25 gleaming grains.', check: g => g.s.stats.gleams >= 25 },
  { id: 'a_sweep1', name: 'Clean Slate', desc: 'Sweep the table.', check: g => g.s.sweeps >= 1 },
  { id: 'a_sweep10', name: 'Ritual', desc: 'Sweep 10 times.', check: g => g.s.sweeps >= 10 },
  { id: 'a_sweep30', name: 'Habit', desc: 'Sweep 30 times.', check: g => g.s.sweeps >= 30 },
  { id: 'a_glass100', name: 'Glazier', desc: 'Hold 100 glass.', check: g => g.s.glass >= 100 },
  { id: 'a_glass1m', name: 'Glass House', desc: 'Hold a million glass.', check: g => g.s.glass >= 1e6 },
  { id: 'a_stone', name: 'Cornerstone', desc: 'Set a stone.', check: g => g.s.owned.stone >= 1 },
  { id: 'a_pocket', name: 'Pocket', desc: 'Make sand linger: one grain dropped somewhere causes 60 topples on average.', check: g => g.bestLinger >= 60 },
  { id: 'a_pocket2', name: 'Labyrinth', desc: 'One grain dropped somewhere causes 250 topples on average.', check: g => g.bestLinger >= 250 },
  { id: 'a_plug', name: 'Plugged', desc: 'Plug a crack with a stone.', check: g => g.s.flags.plugged },
  { id: 'a_trap', name: 'Nowhere to Go', desc: 'Try to trap the sand. It always finds a way.', check: g => g.s.flags.triedTrap },
  { id: 'a_relic1', name: 'Archaeologist', desc: 'Dig up a relic.', check: g => relicCount(g) >= 1 },
  { id: 'a_relic8', name: 'Collector', desc: 'Find 8 relics.', check: g => relicCount(g) >= 8 },
  { id: 'a_relic16', name: 'Antiquarian', desc: 'Find 16 relics.', check: g => relicCount(g) >= 16 },
  { id: 'a_relicall', name: 'Curator', desc: 'Find every relic.', check: g => relicCount(g) >= RELICS.length },
  { id: 'a_tables5', name: 'Wanderer', desc: 'Keep 5 different tables.', check: g => g.s.tablesPlayed >= 5 },
  { id: 'a_tables20', name: 'Cartographer', desc: 'Keep 20 different tables.', check: g => g.s.tablesPlayed >= 20 },
  { id: 'a_fold', name: 'Origami', desc: 'Fold the table.', check: g => g.s.fold },
  { id: 'a_prism', name: 'Spectrum', desc: 'Make a crystal touch three prisms.', check: g => g.s.flags.prism3 },
  { id: 'a_mandala', name: 'Mandala', desc: 'Make a 9×9 or larger table perfectly symmetric (in four mirrors), with at least 100 grains on it.', check: g => g.s.flags.mandala, secret: true },
  { id: 'a_overflow', name: 'Overflowing', desc: 'Have 1,000 grains on a single cell.', check: g => g.s.flags.overflow, secret: true },
  { id: 'a_quick', name: 'Brisk', desc: 'Sweep within 3 minutes of the previous sweep.', check: g => g.s.flags.quickSweep },
  { id: 'a_trial1', name: 'Tested', desc: 'Complete a trial.', check: g => Object.keys(g.s.trials).length >= 1 },
  { id: 'a_trial6', name: 'Proven', desc: 'Complete every trial.', check: g => Object.keys(g.s.trials).length >= 6 },
  { id: 'a_cascade', name: 'Waterfall', desc: 'Build a second table.', check: g => g.boards.length >= 2 },
  { id: 'a_cascade3', name: 'Terraces', desc: 'Build a third table.', check: g => g.boards.length >= 3 },
  { id: 'a_great', name: 'Keeper', desc: 'Complete the Great Hourglass.', check: g => g.s.great >= 5 },
];

// ---------------------------------------------------------------- journal
export const JOURNAL = [
  { id: 'j_start', text: 'A table. A trickle of sand from somewhere above. You put out your hand.', when: () => true },
  { id: 'j_topple', text: 'Four grains is all a place can hold. The fourth sends them tumbling, one to each neighbour.', when: g => g.s.stats.topples >= 1 },
  { id: 'j_dig', text: 'Something is buried near the edge of the table. Sand piled on it shifts, and settles, and shifts.', when: g => g.visibleDigs().length > 0 },
  { id: 'j_hourglass', text: 'An old hourglass in the drawer. It does not measure time so much as spend it.', when: g => g.s.owned.hourglass >= 1 },
  { id: 'j_relic', text: 'A chisel, its handle worn to the shape of a hand like yours. There will be more down there.', when: g => Object.keys(g.s.relics).length >= 1 },
  { id: 'j_table7', text: 'The table is bigger than you remembered. Or you are smaller.', when: g => g.maxSize() >= 7 },
  { id: 'j_geode', text: 'Under the sand, in places, the table glitters. Something wants to grow there.', when: g => g.has('crystal') },
  { id: 'j_crystal', text: 'Crystals grow where the sand falls hardest. They ring when it does.', when: g => g.s.owned.crystal >= 1 },
  { id: 'j_wave', text: 'An avalanche crosses the whole table and you hold your breath the whole way.', when: g => g.s.stats.maxWave >= 25 },
  { id: 'j_quake', text: 'You lean on the table. Everything that was waiting, goes.', when: g => g.s.stats.quakes >= 1 },
  { id: 'j_gleam', text: 'Sometimes a grain catches the light. It seems a shame to let it go.', when: g => g.has('gleam') },
  { id: 'j_kiln', text: 'Behind a curtain: a kiln, still warm. Somebody was here before you.', when: g => g.kilnVisible() },
  { id: 'j_sweep', text: 'The kiln roars. When the smoke clears there is another table, older than the first.', when: g => g.s.sweeps >= 1 },
  { id: 'j_stone', text: 'Stones do not move. Sand goes around them, or back, but never nowhere.', when: g => g.has('stone') },
  { id: 'j_bedrock', text: 'Rock breaks through the sand here. The sand has to go around it, and so do you.', when: g => g.s.seen.t_bedrock },
  { id: 'j_sweep3', text: 'Every table is different. The hands remember what the tables forget.', when: g => g.s.sweeps >= 3 },
  { id: 'j_spring', text: 'A spring! Sand wells up out of the table all on its own.', when: g => g.s.seen.t_spring },
  { id: 'j_doctrine', text: 'There is more than one way to keep a table.', when: g => g.has('doctrine') },
  { id: 'j_slope', text: 'This table leans. Everything poured on it wants to be somewhere else.', when: g => g.s.seen.t_slope },
  { id: 'j_prism', text: 'A prism splits a crystal\'s light, and the crystal sings twice.', when: g => g.has('prism') },
  { id: 'j_crack', text: 'Cracks in the table. Sand falls through, and you never hear it land.', when: g => g.s.seen.t_crack },
  { id: 'j_fold', text: 'You fold the table until its east edge meets its west. The sand does not seem to mind.', when: g => g.s.fold },
  { id: 'j_hundred', text: 'A hundred hourglasses, all pouring onto one spot. The table hums like something alive.', when: g => g.s.owned.hourglass >= 100 },
  { id: 'j_pocket', text: 'Walled in, the sand goes round and round, and every time it falls, it pays.', when: g => g.bestLinger >= 60 },
  { id: 'j_note1', text: 'A note in the drawer, in a hand like yours: "Where the sand cannot leave, it stays. Where it stays, it falls."', when: g => g.s.sweeps >= 6 },
  { id: 'j_relic8', text: 'Eight relics on the shelf. They were all the old keeper\'s. Weren\'t they?', when: g => Object.keys(g.s.relics).length >= 8 },
  { id: 'j_trials', text: 'Another note: "Test yourself. The table will be here when you get back."', when: g => g.has('trials') },
  { id: 'j_trial', text: 'You did it the hard way. The kiln burns a little brighter for it.', when: g => Object.keys(g.s.trials).length >= 1 },
  { id: 'j_trial3', text: 'Halfway through the old keeper\'s tests. Their handwriting is getting steadier, or yours is.', when: g => Object.keys(g.s.trials).length >= 3 },
  { id: 'j_glass', text: 'So much glass that the kiln room glitters. You could see through the walls, if there were still walls.', when: g => g.s.glassAll >= 1e5 },
  { id: 'j_note2', text: 'The notes are getting older, the paper thinner. "Every grain falls off the edge eventually. Where does the edge fall to?"', when: g => g.s.sweeps >= 15 },
  { id: 'j_cascade', text: 'Below your table, another. The sand you thought was lost was only falling.', when: g => g.boards.length >= 2 },
  { id: 'j_cascade3', text: 'Three tables now, like steps down to a river.', when: g => g.boards.length >= 3 },
  { id: 'j_relic16', text: 'You have stopped wondering whose things these are. You know whose hands they fit.', when: g => Object.keys(g.s.relics).length >= 16 },
  { id: 'j_plans', text: 'Plans for an hourglass, larger than the room. Larger than the house. The keeper never finished it.', when: g => g.has('great') },
  { id: 'j_frame', text: 'The frame stands in the dark like a doorway with no wall.', when: g => g.s.great >= 1 },
  { id: 'j_lower', text: 'The lower bulb fills with the sand from your last table. It sounds like rain.', when: g => g.s.great >= 2 },
  { id: 'j_neck', text: 'The neck is so narrow that a grain must wait its turn. Everything does, in the end.', when: g => g.s.great >= 3 },
  { id: 'j_upper', text: 'The upper bulb is empty, and so large that it has weather.', when: g => g.s.great >= 4 },
  { id: 'j_full', text: 'It is full. All of it. Every grain you ever dropped.', when: g => g.s.great >= 5 },
];

// Shown the first time a kind of terrain appears.
export const TERRAIN_TIPS = {
  geode: ['Geodes', 'Glittering cells under the sand. Crystals grow only on geodes, and the further out a geode is, the richer it tends to be.'],
  dig: ['Dig sites', 'Something is buried here. Every topple on a dig site digs a little deeper. Pour sand onto it — or click it — to dig faster.'],
  bedrock: ['Bedrock', 'Rock that sand cannot cross. It reflects sand like a stone, so look for natural pockets to pour into.'],
  spring: ['Springs', 'A spring pours sand all by itself, a fifth as much as all your hourglasses together. Grow crystals near it.'],
  slope: ['Slopes', 'Sand on a slope topples downhill: two grains the way the slope leans, one to each side, none back.'],
  crack: ['Cracks', 'Sand that falls into a crack is gone. Plug cracks with stones, or keep your sand away from them.'],
};
